### ISSUE TITLE
can you show some control result about  the robot 

### ISSUE THREAD

**Issue by yangcopnuli** [srl-ethz/3d-soft-trunk#5]
can you show some control result about  the robot  ,such as the picture of the robot or video link ,thanks

**Comment by Yasu31** [comment]
Sorry that this reply is so late, but here are our papers based on this codebase.

https://ieeexplore.ieee.org/abstract/document/8722799/ - dynamic control
https://ieeexplore.ieee.org/abstract/document/9636539 - dynamic modeling (more of a design proposal paper)

and videos:
https://www.youtube.com/watch?v=AFknWDTHncM
https://www.youtube.com/watch?v=bTD2H4qhzpg
